---
- name: Add Repository
  apt_repository:
          repo: 'ppa:x2go/stable'
- name: Update Repo und install X2goserver
  apt:
          name: "{{ item }}"
          update_cache: yes
  with_items:
          - x2goserver
          - x2goserver-xsession
